service: axiom-serverless-starter

provider:
  name: aws
  runtime: nodejs14.x

package:
  excludeDevDependencies: false
  patterns:
    - "!./**"
    - "./dist/**"

functions:
  example:
    description: An example lambda function
    handler: dist/example.default
    events:
      - http: GET /example
